spring:
  datasource:
    url: jdbc:${DATABASE_PUBLIC_URL}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${PGUSER}
    password: ${PGPASSWORD}
#    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create

